version: '3.5'

networks:
  default:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
    networks:
      - default
  mysql-db:
    container_name: mysql-db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    volumes:
      - mysql-volume:/var/lib/mysql:rw
#      - ./mysql-db:/docker-entrypoint-initdb.d/
    networks:
      - default

volumes:
  mysql-volume: